# Generated by Django 4.1.4 on 2022-12-20 08:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('organization_name', models.CharField(max_length=150, verbose_name='organization_name')),
                ('official_address', models.CharField(max_length=150, verbose_name='official_address')),
                ('state_number', models.DecimalField(decimal_places=0, max_digits=30)),
                ('representative_name', models.CharField(max_length=150, verbose_name='representative_name')),
                ('job_title', models.CharField(max_length=150, verbose_name='job_title')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('state_number',),
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_deal', models.CharField(max_length=100)),
                ('license_type', models.CharField(choices=[('exclusive', 'exclusive'), ('non-exclusive', 'non-exclusive')], max_length=25)),
                ('validity', models.DateField(verbose_name='validity')),
                ('territory', models.CharField(max_length=100)),
                ('ways_to_use', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_info', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'license',
                'verbose_name_plural': 'licenses',
                'ordering': ('creator',),
            },
        ),
        migrations.CreateModel(
            name='LicenseBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.brand')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='license.license')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='brands',
            field=models.ManyToManyField(through='license.LicenseBrand', to='license.brand'),
        ),
    ]
