# Generated by Django 4.1.4 on 2023-01-17 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='license',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='license.license', verbose_name='license'),
        ),
    ]
