# Generated by Django 4.1.4 on 2023-01-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_alter_brand_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='new_deal',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
