# Generated by Django 4.1.4 on 2023-01-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_license_new_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='license',
        ),
        migrations.AlterField(
            model_name='license',
            name='new_deal',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='license',
            field=models.ManyToManyField(null=True, related_name='brand', to='license.license', verbose_name='license'),
        ),
    ]
