# Generated by Django 4.1.4 on 2022-12-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_license_brand_alter_license_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
