# Generated by Django 4.1.4 on 2022-12-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0004_alter_license_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='content',
        ),
    ]
