# Generated by Django 4.1.4 on 2022-12-18 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_remove_license_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
