# Generated by Django 4.1.4 on 2022-12-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0008_remove_license_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
