# Generated by Django 4.1.4 on 2022-12-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='id_number',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=30),
            preserve_default=False,
        ),
    ]
