# Generated by Django 4.1.4 on 2022-12-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_creator_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='id_number',
            field=models.DecimalField(decimal_places=0, max_digits=30, null=True),
        ),
    ]
