# Generated by Django 4.1.4 on 2022-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_creator_address_alter_creator_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='name_surname',
            field=models.CharField(max_length=150, unique=True, verbose_name='name_surname'),
        ),
    ]
