# Generated by Django 4.1.4 on 2022-12-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_creator_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='address',
            field=models.CharField(max_length=150, unique=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='id_number',
            field=models.DecimalField(decimal_places=0, max_digits=30, null=True, unique=True),
        ),
    ]
